name: Deploy Newsbox Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: SSH to VPS & Rebuild Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ -d "$HOME/Newsbox---discord-bot" ]; then
              cd "$HOME/Newsbox---discord-bot"
            elif [ -d "/root/Newsbox---discord-bot" ]; then
              cd "/root/Newsbox---discord-bot"
            fi
            echo "Working directory: $(pwd)"
            git pull origin main
            sudo docker compose up -d --build
